module.exports = (sequelize, DataTypes) => {
    const Quiz = sequelize.define('Quiz', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        chapterId: {
            type: DataTypes.INTEGER,
            allowNull: false,
            field: 'chapter_id',
            references: {
                model: 'chapters',
                key: 'id'
            }
        },
        title: {
            type: DataTypes.STRING(255),
            allowNull: false
        },
        description: {
            type: DataTypes.TEXT,
            allowNull: true
        },
        difficulty: {
            type: DataTypes.STRING(20),
            defaultValue: 'medium',
            validate: {
                isIn: [['easy', 'medium', 'hard']]
            }
        },
        isAutoGenerated: {
            type: DataTypes.BOOLEAN,
            defaultValue: false,
            field: 'is_auto_generated',
            comment: 'Whether this quiz was AI-generated'
        },
        timeLimit: {
            type: DataTypes.INTEGER,
            allowNull: true,
            field: 'time_limit',
            comment: 'Time limit in minutes (null for no limit)'
        },
        passingScore: {
            type: DataTypes.INTEGER,
            defaultValue: 70,
            field: 'passing_score',
            comment: 'Minimum percentage to pass'
        },
        totalQuestions: {
            type: DataTypes.INTEGER,
            defaultValue: 0,
            field: 'total_questions'
        },
        isActive: {
            type: DataTypes.BOOLEAN,
            defaultValue: true,
            field: 'is_active'
        }
    }, {
        tableName: 'quizzes',
        timestamps: true,
        underscored: true
    });
    return Quiz;
};

